# Generated by Django 4.2.5 on 2023-09-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notification_tag',
            field=models.CharField(default='AftU5O6se4uCReolq20H', help_text="Chaine de caractère aléatoire à renseigner dans l'application pour recevoir les notifications", max_length=20, verbose_name='Tag de notification'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('persons', models.ManyToManyField(related_name='teams', to='base.person', verbose_name='personnes')),
                ('users', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
