# Generated by Django 4.2.16 on 2024-10-01 21:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_customuser_notification_tag_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Équipe", "verbose_name_plural": "Équipes"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="notification_tag",
            field=models.CharField(
                default="dimJRvG3naoBgrGoV3ln",
                help_text="Chaîne de caractère aléatoire à renseigner dans l'application pour recevoir les notifications",
                max_length=20,
                verbose_name="Tag de notification",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birthdate",
            field=models.DateField(verbose_name="Date d’anniversaire"),
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Intitulé"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="base.person",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de téléphone",
                "verbose_name_plural": "Numéros de téléphone",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Intitulé"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="base.person",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
    ]
